// src/components/SupportPage/SupportPage.jsx

import React from 'react';
import './SupportContact.css'; // We'll share a stylesheet with the Contact page

function SupportPage() {
  return (
    <div className="sc-page-container">
      <header className="sc-page-header">
        <h1>Support Center</h1>
        <p>Your questions, answered. Find help with our most common inquiries below.</p>
      </header>

      <section className="sc-content-section">
        <h2>Frequently Asked Questions</h2>
        
        <div className="faq-item">
          <h3>How does PlagiX detect AI-generated content?</h3>
          <p>
            PlagiX uses advanced machine learning models trained on vast datasets of human and AI-generated text. Our algorithms analyze linguistic patterns, sentence structure, and other markers to determine the probability of a text being generated by an AI.
          </p>
        </div>

        <div className="faq-item">
          <h3>What languages does PlagiX support?</h3>
          <p>
            Our platform supports over 15 languages, with a special focus on major Indian languages including Hindi, Marathi, Bengali, and Telugu, in addition to English, Spanish, and more.
          </p>
        </div>

        <div className="faq-item">
          <h3>Is my data secure when I upload a document?</h3>
          <p>
            Absolutely. We prioritize your privacy and data security. All uploaded documents are encrypted and are not used for any purpose other than generating your plagiarism report. They are never shared or added to any public database.
          </p>
        </div>

        <div className="faq-item">
          <h3>How do I integrate PlagiX with my Learning Management System (LMS)?</h3>
          <p>
            We offer seamless integration with popular LMS platforms like Moodle, Canvas, and Blackboard. Please visit our 'Partners' page or contact our support team for detailed integration guides.
          </p>
        </div>
      </section>
    </div>
  );
}

export default SupportPage;
