# report_generator.py

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime

def generate_pdf_report(student_name, new_file_name, top_match, similarity, grammar_issues, grammar_list, output_path):
    c = canvas.Canvas(output_path, pagesize=A4)

    # ------------ HEADER ------------
    c.setFont("Helvetica-Bold", 18)
    c.drawString(150, 800, "Plagiarism Report")

    c.setFont("Helvetica", 12)
    c.drawString(50, 760, f"Student Name: {student_name}")
    c.drawString(50, 740, f"File Checked: {new_file_name}")
    c.drawString(50, 720, f"Most Similar Document: {top_match}")
    c.drawString(50, 700, f"Similarity Percentage: {similarity:.2f}%")
    c.drawString(50, 680, f"Grammar Issues Found: {grammar_issues}")
    c.drawString(50, 660, f"Checked On: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 640, "This report is auto-generated by Student Plagiarism Checker.")

    # ------------ GRAMMAR DETAILS ------------
    y = 610
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Detailed Grammar Issues:")
    y -= 20

    c.setFont("Helvetica", 10)

    for idx, err in enumerate(grammar_list):

        # Page break
        if y < 80:
            c.showPage()
            y = 800
            c.setFont("Helvetica-Bold", 14)
            c.drawString(50, y, "Detailed Grammar Issues (Continued):")
            y -= 20
            c.setFont("Helvetica", 10)

        c.drawString(50, y, f"Issue {idx+1}: Wrong word → '{err['word']}'")
        y -= 15
        c.drawString(70, y, f"Type: {err['issue']}")
        y -= 15
        c.drawString(70, y, f"Message: {err['message']}")
        y -= 15
        c.drawString(70, y, f"Suggestion: {err['suggestion']}")
        y -= 25

    c.save()
